baseURL = "https://yitaoli/"
title = "æä¸€æ¡ƒ ğŸ‘"

theme = "puppet"

copyright = ""
paginate = 10
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = "G-040GK8YC1C"

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "ä¸»é¡µ"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "æ–‡ç« "
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "about"
name = "å…³äºæˆ‘"
url = "/about/"
weight = 50


[params]
author = "æä¸€æ¡ƒğŸ‘"
description = "æˆ‘ä»¬çº¢å°˜åšä¼´ï¼Œæ´»å¾—æ½‡æ½‡æ´’æ´’"
keywords = "åšå®¢ï¼Œç”Ÿæ´»ï¼Œå“ˆå£«å¥‡ï¼Œç§‘æŠ€"
img_home = "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80"
img_404 = "https://images.unsplash.com/photo-1651940334832-6346cf9276ee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/echo.png"
bio = "æµªè¿¹å¤©æ¶¯èµ°èµ·"

[params.social]
rss = true
[params.social.mastodon]
weight = 56
icon = "fab fa-mastodon"
format = "https://o3o.ca/%v"
id = "@yttttting"
url = "https://o3o.ca/@yttttting"

[params.social.instagram]
weight = 56
icon = "fab fa-instagram"
format = "https://www.instagram.com/%v"
id = "@yitao.li23"
url = "https://www.instagram.com/yitao.li23/"

[params.social.youtube]
weight = 56
icon = "fab fa-youtube"
format = "https://www.youtube.com/%v"
id = "@yitaoli"
url = "https://www.youtube.com/@yitaoli"

[[params.friends]]
name = "å‘¼çŒ«æŠ¤å«"
url = "https://www.notion.so/qingshanbadass/e3d519283a9f4412acc1d174ec94e30d"

[[params.friends]]
name = "æ¤’ç›è±†è±‰"
url = "https://blog.douchi.space/#gsc.tab=0"

[[params.friends]]
name = "Nomadland"
url = "https://nomadland.blog/"

[[params.friends]]
name = "Shingi"
url = "https://www.shingireservation.com/"

# See https://giscus.app/
[params.giscus]
enable = true
repo = "yitaoli2023/yitaoli"
repo_id = "R_kgDOJu1maA"
category = "General"
category_id = "DIC_kwDOJu1maM4CXMl7"
mapping = "title"
input_position = "top"
theme = "light_tritanopia"
lang = "zh-CN"